name: 'Remote run'
description: 'Run shell code on a remote server using ssh'

inputs:
  run:
    description: 'The remote shell code to run'
    required: true

  target:
    description: 'The target server to run code on'
    default: 'server.test'
    required: true

  working-directory:
    description: 'The working directory to run shell code in'
    default: '$HOME'
    required: false

runs:
  using: 'composite'
  steps:
    - shell: sh
      name: Execute remote shell
      run: |
        ssh -T ${{ inputs.target }} << EOF
          set -ex
          cd "${{ inputs.working-directory }}"
          ${{ inputs.run }}
        EOF
