name: 'Create tag'
description: 'Create a new git repository tag'

inputs:
  git-tag:
    description: 'Git tag nme'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Create tag
      uses: actions/github-script@v6
      with:
        github-token: ${{ github.token }}
        script: |
          try {
            // Delete existing tag if found
            await github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "tags/${{ inputs.git-tag }}",
            })

            await github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "tags/${{ inputs.git-tag }}",
            });
          } catch (e) {
            // Catch not found exception
          }

          console.log('Creating new tag "${{ inputs.git-tag }}".');
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/${{ inputs.git-tag }}",
            sha: context.sha
          });
